# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'SolidRockAppTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SolidRockAppTemplate
  pod 'SDWebImage', '~> 4.0'

  target 'SolidRockAppTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SolidRockAppTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
